' DEMO OF PSGMINI - SN76489 + NES APU SIMULATOR - VGM PLAYER
' MAURO XAVIER 2020
'

#INCLUDE "PSGMINI.INC"

 CLS: TEST=0
 DIM XGR(4),YGR(4),CS(MM.HRES)

 ' PRE CALCULATE COS
 CC=90
 FOR T=1 TO MM.HRES
  CC=CC+0.015
  CS(T)=COS(CC)*2
 NEXT T 

 InitSound

 MODE 1,8
 COLOR RGB(255,255,255),RGB(0,0,0): CLS: PAUSE(100)
 FOR T=0 TO 3: PAGE WRITE T: CLS: NEXT T

 IF TEST=1 THEN GOTO TESTING
 'Goto Testing
 PAGE WRITE 1: CLS: LOAD PNG ".\ASSETS\PSGMINI_800X600.PNG",,,0
 
 PAGE WRITE 0: I=0:II=0
 LoadVGM(".\ASSETS\PSGMINI.VGM")
 PlayVGM:SetIntVGM(1):ChangeSpeed(1)
 SetChannelType(1,"Q"): SetChannelType(2,"Q"): SetChannelType(3,"Q")

 FOR TT=75 TO 0 STEP -2
  I=II
  II=II+1
  FOR T=195 TO 195+157
   I=I+0.1
   BLIT 0,T,COS(I)*TT,T,MM.HRES-COS(I)*TT,1,1,0  
  NEXT T
  PAUSE(10)
 NEXT TT 

 BLIT 0,195,0,195,MM.HRES,157,1,0

 BLIT 0,MM.VRES-30,0,MM.VRES-70,MM.HRES,20,1,0
 PAGE WRITE 1
 BOX 0,MM.VRES-200,MM.HRES,169,0,RGB(0,0,0),RGB(0,0,0)

 PAUSE(2000)
 StopVGM: UnloadVGM
 Play Stop

 PAGE WRITE 2: CLS: LOAD PNG ".\ASSETS\FONTS.PNG",,,8
 PAGE WRITE 3: CLS: LOAD PNG ".\ASSETS\BIG_FONTS.PNG",,,8

 ' START ANIMATION 
 PAGE WRITE 0
 D=5:X=0
 BOX MM.HRES/2-1,195,2,157,0,RGB(0,0,0),RGB(0,0,0)
 FOR TT=450 TO 0 STEP -D
  X=X+1
  IF X<50 THEN 
   BOX MM.HRES\2-X*8,195,X*16,157,0,RGB(0,0,0),RGB(0,0,0)
   'BLIT X,195,1,195,MM.HRES\2-X,157,0,0:PAUSE(10)
   'BLIT MM.HRES\2,195,MM.HRES\2+X,195,MM.HRES\2-X,157,0,0:PAUSE(10)
  ENDIF
  FOR T=0 TO 3
   BLIT 0,MM.VRES-30,0,MM.VRES-70,MM.HRES,20,1,0
   SELECT CASE T
    CASE 0,2: 
     BOX 80+T*180-D, 180-D  -TT, 90+D*2, 300+D*2, D, RGB(255,255,255)
     BOX 80+T*180-D, 180-D*3-TT, 90+D*2,     D*2, D, RGB(0,0,0)
     BOX 80+T*180,   480-D*2-TT, 90,         D*2, D, RGB(0,0,0)
    CASE 1,3: 
     BOX 80+T*180-D, 180-D  +TT, 90+D*2, 300+D*2, D, RGB(255,255,255)
     BOX 80+T*180-D, 480+D*1+TT, 90+D*2,     D*2, D, RGB(0,0,0)
     BOX 80+T*180,   180+D*0+TT, 90,         D*2, D, RGB(0,0,0)
   END SELECT
  PAUSE(1)
  PLAY SOUND 1,B,N,460-TT+1,25
 NEXT T,TT
 
 FOR T=25 TO 1 STEP-1
  PAGE SCROLL 0,0,COS(T/2-0.1)*2
  PLAY SOUND 1,B,N,100-T,T
  PAUSE(20)
 NEXT T
 PLAY STOP
 
 PAGE WRITE 1 
 FOR T=0 TO 3
  PRINTS(112+T*180,MM.VRES-110,2,STR$(T+1))
  FOR TT=0 TO 255
    IF TT>127 THEN 
     BOX 80+T*180-D, 180-D, 90+D*2, 300-TT*1.2+D*2, D, RGB(255,255-(TT-128)*2,0)
     BOX 80+T*180  ,   180,     90, 300, 0, RGB(0,0,0), RGB(0,0,0)
    ELSE
     BOX 80+T*180-D, 180-D, 90+D*2, 300-TT*1.2+D*2, D, RGB(TT*2,255,0)
     BOX 80+T*180  ,   180,     90, 300, 0, RGB(0,0,0), RGB(0,0,0)
    ENDIF
   PAGE WRITE 0
   BLIT 80+T*180-D,180-D,80+T*180-D,180-D,90+D*2,320+D*2,1,0
   PAGE WRITE 1
   PLAY SOUND 1,B,N,200-TT/3,25
  NEXT TT
  PAUSE(50)
 NEXT T
 PLAY STOP
 PAGE COPY 0 TO 1

 TESTING:

 PLMUS=5: MESX=1
 
 DIM MES%(2000)
 LONGSTRING CLEAR MES%()
 LONGSTRING APPEND MES%(),"  |2PRESS UP AND DOWN TO CHANGE THE MUSIC ... "
 LONGSTRING APPEND MES%(),"HI! THIS IS A LITTLE DEMONSTRATION OF WHAT THE |3COLOUR "
 LONGSTRING APPEND MES%(),"MAXIMITE 2|2 CAN BRING TO YOU! WOULD YOU LIKE TO HEAR A SIMULATION OF "
 LONGSTRING APPEND MES%(),"THE OLD AND GOOD SOUND CHIPS FROM THE PAST? ...|0 SN76489    AY-3-8910    "
 LONGSTRING APPEND MES%(),"C64 SID    ATARI POKEY    NES APU 2A03    AND WHO KNOWS MAYBE OTHERS? "
 LONGSTRING APPEND MES%(),"|2WAIT! DID I SAY SIMULATION? YES! IT'S NOT AN EMULATION, IT'S ONLY SOME "
 LONGSTRING APPEND MES%(),"TRICKS USING THE SOUND WAVE CAPABILITIES FROM THIS INCREDIBLE MACHINE "
 LONGSTRING APPEND MES%(),"... AND IT'S NOT ALL!   |1WE HAVE NOT 3 ...  NOT 4 ... NOT 5 ... "
 LONGSTRING APPEND MES%(),"BUT EIGHT STEREO SOUND CHANNELS|2 DEDICATED TO PLAY "
 LONGSTRING APPEND MES%(),"VARIOUS TYPES OF WAVE: SQUARE, TRIANGLE, SINE, SAWTOOTH, "
 LONGSTRING APPEND MES%(),"WHITE NOISE, AND PERIODIC NOISE ...|2 WITH THIS YOU CAN MAKE "
 LONGSTRING APPEND MES%(),"|0GAMES WITH CHIPTUNE MUSIC|2 AND SOUND EFFECTS WITH PRACTICALLY "
 LONGSTRING APPEND MES%(),"NO EFFORTS!  ... WHAT? DO YOU DON'T KNOW HOW TO MAKE MUSIC? "
 LONGSTRING APPEND MES%(),"NO PROBLEM!  YOU CAN USE |0VGM FILES|2 FOR THE BACKGROUND MUSIC "
 LONGSTRING APPEND MES%(),"AND WITH EASY COMMANDS FROM |3MMBASIC|2 YOU CAN MAKE SOME GOOD |0RETRO SOUND "
 LONGSTRING APPEND MES%(),"EFFECTS|2, IT'S A PIECE OF CAKE! ARE YOU NOT CONVINCED YET?  "
 LONGSTRING APPEND MES%(),"... THEN STOP THIS DEMO PROGRAM AND ENJOY THE SOURCE CODE! ... "
 LONGSTRING APPEND MES%(),"I MUST THANKS TO THE DEVELOPERS THAT BROUGHT THE |3COLOUR MAXIMITE 2 "
 LONGSTRING APPEND MES%(),"TO LIFE:  |0MATHERP |2(THE GENIUS BEHIND THE FIRMWARE AND PROJECT "
 LONGSTRING APPEND MES%(),"LEADER) AND |0GEOFFG |2(THE FATHER OF THE ORIGINAL MMBASIC AND CMM) AND "
 LONGSTRING APPEND MES%(),"OTHER AWESOME PEOPLE THAT HELPED TO MAKE THE |3CMM2|2 BETTER YET: "
 LONGSTRING APPEND MES%(),"|0CEPTIMUS   CIRCUITGIZMOS   GROGSTER   TASSYJIM|2  AND|0  WHITEWIZZARD "
 LONGSTRING APPEND MES%(),"|2   ...   __"

 CONAY$="CONVERTED AY-3-8192 TO SN76489"
 SID$  ="SID STYLE USING SAWTOOTH WAVE"
 SNORG$="SN76489 ORIGINAL"
 NESAPU$="NES APU"

 SMS$=  "SEGA Master System"
 GG$=   "SEGA Game Gear"
 ATST$= "Atari ST"
 MSX$=  "MSX"
 ZX$=   "ZX Spectrum"
 NES$=  "Nintendo Entertainment System"

 FIRSTTIME=2

 SELECTION = 1

 DO WHILE SELECTION = 1 

  FROM$=SMS$
  MUSTYP$=SNORG$
  MTSpd=1
 
  SELECT CASE PLMUS
   CASE  1: MT$="ALESTE": NMUS$="Aleste Theme"
   CASE  2: MT$="TRIUMPH": NMUS$="Aleste Ending Theme"
   CASE  3: MT$="GAINGROUND": NMUS$="Gain Ground Stage 1"
   CASE  4: MT$="SPIROU_BOSS": NMUS$="Spirou Boss Theme": FROM$=GG$
   CASE  5: MT$="SPIROU_BOSS": NMUS$="Spirou Boss Theme": FROM$=GG$: MUSTYP$=SID$
   CASE  6: MT$="SPIROU_METRO": NMUS$="Spirou Metro Theme": FROM$=GG$
   CASE  7: MT$="SPIROU_METRO": NMUS$="Spirou Metro Theme": FROM$=GG$: MUSTYP$=SID$
   CASE  8: MT$="ALEXKIDD": NMUS$="Alex Kidd Theme"
   CASE  9: MT$="AWESOME": MTSpd=1.1: NMUS$="Awesome": FROM$=ATST$: MUSTYP$=CONAY$
   CASE 10: MT$="ROBOCOP": MTSpd=1.1: NMUS$="Robocop Stage 1": FROM$=MSX$: MUSTYP$=CONAY$
   CASE 11: MT$="ESWAT_LEVEL5": NMUS$="E-Swat Level 5"
   CASE 12: MT$="SONIC": NMUS$="Sonic Green Hill Zone"
   CASE 13: MT$="ROBOCOP_SMS": NMUS$="Robocop Stage 1": MTSpd=1.1
   CASE 14: MT$="SUPER_MARIO": NMUS$="Super Mario Bros Theme": FROM$=NES$: MUSTYP$=NESAPU$
   CASE 15: MT$="KAGE2": NMUS$="Shadow of the Ninja Stage 2": FROM$=NES$: MUSTYP$=NESAPU$
   CASE 16: MT$="GOLDENAXE": NMUS$="Golden Axe Intro": FROM$=ATST$: MUSTYP$=CONAY$: MTSpd=1.1
   CASE 17: MT$="GOLDENAXE": NMUS$="Golden Axe Intro": FROM$=ATST$: MUSTYP$=SID$: MTSpd=1.1
   CASE 18: MT$="BATTLETOADS2": NMUS$="Battletoads in Battlemaniacs": MTSpd=1.1
   CASE 19: MT$="BATTLETOADS2": NMUS$="Battletoads in Battlemaniacs": MUSTYP$=SID$: MTSpd=1.1
   CASE 20: MT$="TITANIC": NMUS$="Titanic Intro Theme": FROM$=ZX$: MUSTYP$=CONAY$: MTSpd=1.1
   CASE 21: MT$="TITANIC": NMUS$="Titanic Intro Theme": FROM$=ZX$: MUSTYP$=SID$: MTSpd=1.1
  END SELECT

  'PAGE COPY 0 TO 1
  PAGE WRITE 1: BOX 0,0,MM.HRES,175,1,RGB(0,0,0),RGB(0,0,0)

  ' DRAW SOUND BAR
  'IF FIRSTTIME=1 THEN
  ' D=5
  ' FOR T=0 TO 3
  '  PRINTS(112+T*180,MM.VRES-110,2,STR$(T+1))
  '  FOR TT=0 TO 255 
  '    BOX 80+T*180-D, 180-D, 90+D*2, 300-TT+D*2, D, RGB(178.6+TT/4.98,255-TT,TTT)
  '  NEXT TT
  '  BOX 80+T*180  ,   180,       90, 300, 0, RGB(0,0,0), RGB(0,0,0)
  ' NEXT T
  'ENDIF

  if MtSpd=1 then A$="60Hz" else A$="50Hz"

  Y=0
  IF FIRSTTIME=1 THEN Y=-120: PAGE WRITE 1

  IF FIRSTTIME<2 THEN
   PRINTS(0, 60,4,"    MUSIC: " + UCASE$(NMUS$))
   PRINTS(0, 80,4,"  MACHINE: " + UCASE$(FROM$))
   PRINTS(0,100,4,"PLAY TYPE: " + UCASE$(MUSTYP$) + " - " + UCASE$(A$))
  ENDIF

  PAGE WRITE 0
  DO WHILE Y<0
   IF Y<0 THEN Y=Y+1: BLIT 0,0,0,Y,MM.HRES,120,1,0: PAUSE(2)
  LOOP
 
  IF FIRSTTIME=1 THEN PAGE COPY 1 TO 0 ELSE BLIT 0,0,0,0,MM.HRES,175,1,0

  If ChangeMus=1 then 
   UnloadVGM
   if test=0 then
    LoadVGM(".\ASSETS\"+MT$+".VGM")
   else    
    LoadVGM("A:\PSGMINI\ASSETS\SUPER_MARIO.VGM")
    'LoadVGM("A:\MSTUDIO\SN76489\FROM_YM\TOKI\TOKI3.VGM")
    'LoadVGM("A:\MSTUDIO\SN76489\SHIRU\MYMISTAK.VGM")
   endif
  endif
  ChangeMus=0
  IF FIRSTTIME=0 THEN PlayVGM: SetIntVGM(1): MtSpd=1:ChangeSpeed(MtSpd)
  IF TEST=1 THEN CHANGESPEED(1)
  IF (PLMUS >=1 AND PLMUS <=13) OR PLMUS=16 THEN
   SetChannelType(1,"Q"): SetChannelType(2,"Q"): SetChannelType(3,"Q")
  ENDIF
  IF PLMUS = 21 THEN
   SetChannelType(1,"W"): SetChannelType(2,"Q"): SetChannelType(3,"Q")    
  ELSEIF MUSTYP$=SID$ THEN
   SetChannelType(1,"Q"): SetChannelType(2,"W"): SetChannelType(3,"Q")
   IF PLMUS=17 OR PLMUS=19 THEN SetChannelType(1,"T"): SetChannelType(3,"T")
   IF PLMUS=5 OR PLMUS=7 THEN SetChannelType(1,"W"): SetChannelType(2,"W"): SetChannelType(3,"W")
  ENDIF
  IF MUSTYP$=NESAPU$ THEN
   if PLMUS=14 THEN SetChannelType(1,"Q"): SetChannelType(2,"Q")
   if PLMUS=15 THEN SetChannelType(1,"W"): SetChannelType(2,"W")
   SetChannelType(3,"T"): SetChannelType(4,"N")
  ENDIF
  ChTypeAnt$=""
  SetChannelSide(1,"L")
  SetChannelSide(2,"L")
  SetChannelSide(3,"R")
  SetChannelSide(4,"R")
  
  IF TEST=1 THEN 
    SetChannelSide(1,"B")
    SetChannelSide(2,"B")
    SetChannelSide(3,"B")
    SetChannelSide(4,"B")    
    FROM$=SMS$
    MUSTYP$=SNORG$
    MTSpd=1: PLMUS=1
   SetChannelType(1,"Q"): SetChannelType(2,"Q"): SetChannelType(3,"Q")
  ENDIF
  
  IF FIRSTTIME=0 THEN
   FOR T=0 TO 3
    SELECT CASE ChType$(T)
     CASE "W": A$="SAWTOOTH"
     CASE "Q": A$="SQUARED"
     CASE "T": A$="TRIANGLE"
     CASE "S": A$="SINE"
     CASE "P","W2": A$="NOISE"
     CASE "N": A$="NOISE"
    END SELECT
    PRINTS(116+T*180-LEN(A$)*4,160,1,A$)
   NEXT T 
  ENDIF
  DO WHILE KEYDOWN(1)=0 AND FIRSTTIME=0
   SndGraf
  LOOP
    
  KB=KEYDOWN(1)
  IF KB=27 THEN SELECTION = 0
  IF KB=128 THEN PLMUS=PLMUS-1: ChangeMus=1
  IF KB=129 THEN PLMUS=PLMUS+1: ChangeMus=1
  IF PLMUS>19 THEN PLMUS=1
  IF PLMUS<1 THEN PLMUS=19 
 
  IF FIRSTTIME=1 THEN LoadVGM(".\ASSETS\"+MT$+".VGM")

  DO WHILE KEYDOWN(1)<>0 AND FIRSTTIME=0
   SndGraf   
  LOOP

  FIRSTTIME=FIRSTTIME-1:IF FIRSTTIME<=0 THEN FIRSTTIME=0

 LOOP
 StopVGM: UnloadVGM: CLS: End  
ENDIF

Sub SndGraf
 LOCAL ST,SIZE,T,TT,CO,N
 ST=MM.VRES-120
 IF FROM$=NES$ THEN N=1
 FOR T=0+N TO 3+N '* (5-ChVol(T)/3)
  IF N=1 THEN
   if EnableCh(T)=1 and ChVol(T)>1 and (Counter(T)>0 or HaltFlag(t)=1) then
    NEStmp=Val("&B"+TonA$(T)+TonB$(T))
    if T<>3 then Ton(T)=NESCLK/(16*(NEStmp+1)) else Ton(T)=NESCLK/(32*(NEStmp+1))
    If Ton(T)>20000 then Ton(T)=20000
    SELECT CASE T
     CASE 1 TO 2: SIZE=(Ton(T)/12)*(ChVol(T))/3
     CASE 3: SIZE=(Ton(T)/4)
     CASE 4: SIZE=(Ton(T)/6)*(ChVol(T))/3
    END SELECT
    if NESTmp<=8 and T=3 then Ton(3)=0
   else
    Ton(T)=0
   endif
  ELSE
   IF T<3 THEN SIZE=(Ton(T)/12)*(15-ChVol(T))/3 ELSE SIZE=(300-ChVol(3)*19)
  ENDIF
  IF SIZE>300 THEN SIZE=300
  IF SIZE<0 THEN SIZE=0
  XGR(T)=80+(T-N)*180: YGR(T)=ST-SIZE
  BOX XGR(T), 180,   90,300-SIZE, 0, RGB(0,0,0), RGB(0,0,0)
  BOX XGR(T), YGR(T),90,    SIZE, 0, RGB(0,0,0), RGB(255,255,255)
 NEXT T

 SPD=8
 LX=LX+SPD: IF LX>30+SPD THEN LX=0:MESX=MESX+1
 IF CHR$(Peek(VAR MES%(),MESX))="_" THEN MESX=1
 IF CHR$(Peek(VAR MES%(),MESX))="|" THEN TP=VAL(CHR$(Peek(VAR MES%(),MESX+1))):MESX=MESX+2
 PRINTB(MM.HRES-LX-32,MM.VRES-90,TP,CHR$(Peek(VAR MES%(),MESX)))
 TT=0
 'BLIT 2,MM.VRES-100,0,MM.VRES-100,MM.HRES-2,32,0,0 
 FOR T=SPD TO MM.HRES STEP SPD
  TT=TT+1  
  BLIT T,MM.VRES-100,T-SPD,MM.VRES-100+CS(T),SPD,80,0,0
 NEXT T
 BOX MM.HRES-SPD,MM.VRES-100,SPD,42,1,RGB(0,0,0),RGB(0,0,0)

 IF ChTypeAnt$<>ChType$(3) then
  A$="WHITE"
  SELECT CASE ChType$(3)
   CASE "P","W2": A$="PERIODIC"
  END SELECT
  BOX 116+3*180-40,150,80,8,1,RGB(0,0,0),RGB(0,0,0)
  PRINTS(116+3*180-LEN(A$)*4,150,1,A$)
  ChTypeAnt$=ChType$(3)
 Endif
End Sub

' "SMALL" FONTS
Sub PrintS(x,y,tp,st$)
 Local T,LX,LY,sx,sy
 SX=8
 SELECT CASE TP
  CASE -2: SX=6
  CASE -1: SX=5
  CASE >=4: SX=16
 END SELECT
 FOR T = 1 TO LEN(st$)
  SELECT CASE TP
   CASE <=3: LY=25+TP*16: IF TP=3 THEN SY=16 ELSE SY=8
   CASE >3: LY=105+(TP-4)*48: SY=16
  END SELECT
  LX=(ASC(mid$(st$,t,1))-32)*sx
  IF LX>=640 THEN LX=LX-640:LY=LY+sy*2 
  IF LX>=320 THEN LX=LX-320:LY=LY+sy 
  IF TP=-2 THEN LY=0:SX=5:SY=9
  BLIT LX,LY,x+T*sx,y,sx,sy,2,4
 NEXT T
End Sub

' "BIG" FONTS
Sub PrintB(x,y,tp,st$)
 Local T,TT,LX,LY,sx,sy
 SX=32
 FOR T = 1 TO LEN(st$)
  SELECT CASE TP
   CASE 0: LY=0:   SY=32
   CASE 1: LY=96:  SY=30
   CASE 2: LY=186: SY=25
   CASE 3: LY=261: SY=25
  END SELECT
  LX=(ASC(mid$(st$,t,1))-32)*sx  
  for tt=3 to 1 step -1
   IF LX>=640*tt THEN LX=LX-640*tt:LY=LY+sy*tt
  next tt
  BLIT LX,LY,x+T*sx,y,sx,sy,3,4
 NEXT T
End Sub



